# Use container based infra
sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - nightly

cache:
  - pip

install:
  - make init
  - pip install tox-travis

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
