# Use container based infra
sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - nightly

cache:
  - pip
  - apt

addons:
  apt:
    packages:
      - dbus
      - libdbus-1-dev
      - libdbus-glib-1-dev

before_install:
  - echo "Python diagnostic Information"
  - python --version
  - python-config --includes
  - python-config --libs
  - python-config --ldflags

install:
  - make init
  - pip install tox-travis

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
